@startuml
'https://plantuml.com/state-diagram

adventure : **setLocation("The Goblin Cave")**
adventure : collectLoot()
adventure : tire()

restInCamp : **setUpCamp()**
restInCamp : rest()
restInCamp : __packUpCamp()__

sellLoot : **setLocation("Pawn Aplenty")**
sellLoot : sellLoot()

drinkAtInn : **setLocation("The Golden Goblin")**
drinkAtInn : buyAle()
drinkAtInn : drinkAle()

[*] --> adventure
adventure --> restInCamp : isTired
restInCamp --> adventure : isFullyRecovered
adventure --> sellLoot : bagsAreFull
sellLoot --> drinkAtInn : bagsAreEmpty
drinkAtInn -> adventure : hasNoMoreGold

@enduml